version: '2.1'
services:
  mysql:
    image: harbor.emotibot.com/library/mysql:5.7
    container_name: mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - TZ=Asia/Taipei
    mem_limit: 5125m
    volumes:
    - ${VOLUME_PATH}/mysql:/var/lib/mysql
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute=\"SHOW DATABASES;\""
      interval: 3s
      timeout: 3s
      retries: 20

  redis:
    image: harbor.emotibot.com/library/redis:3.2.9
    container_name: redis
    ports:
    - 6379:6379
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    command: redis-server --requirepass password

  minio:
    container_name: minio
    image: harbor.emotibot.com/bfop/minio:RELEASE.2019-05-02T19-07-09Z
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    environment:
    - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
    - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    - MINIO_SECURE=${MINIO_SECURE}
    restart: always
    volumes:
    - ${VOLUME_PATH}/miniogw/data:/data
    - ${VOLUME_PATH}/miniogw/ssl:/root/.minio/certs
    command: server /data
    ports:
    - 9000:9000

  standalone-chrome:
    container_name: standalone-chrome
    image: harbor.emotibot.com/gemini/standalone-chrome:3.141.59-zinc
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 1M
    ports:
    - ${WEBDRIVER_PORT}:${WEBDRIVER_PORT}
    shm_size: 2g
    restart: always

  stock-task-ui:
    image: harbor.emotibot.com/yanbin/stock-task-ui:ca17015c-20201116-2307
    container_name: stock-task-ui
    ports:
    - ${STOCK_TASK_UI_PORT}:${STOCK_TASK_UI_PORT}
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    environment:
      - STOCK_TASK_UI_PORT=${STOCK_TASK_UI_PORT}
      - STOCK_ADMIN_URL=${STOCK_SECURITY_HOST}:${STOCK_SECURITY_PORT}
      - STOCK_TASK_URL=${STOCK_TASK_HOST}:${STOCK_TASK_PORT}
    restart: always

  stock-task-service:
    image: harbor.emotibot.com/stock/stock-task-service:064a8f8-20201117
    container_name: stock-task-service
    ports:
    - 1700:1700
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    environment:
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PORT=${REDIS_PORT}
    - REDIS_PASS=${REDIS_PASS}
    - REDIS_ENABLE=true
    - MINIO_HOST=${MINIO_HOST}
    - MINIO_PORT=${MINIO_PORT}
    - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
    - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    - MYSQL_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/crawl?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    - MYSQL_USERNAME=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASS}
    - SPIDER_URL=http://${SPIDER_HOST}:${SPIDER_PORT}

  stock-security-service:
    image: harbor.emotibot.com/stock/stock-security-service:7fbd908-20201115
    container_name: stock-security-service
    ports:
    - 7879:7879
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    environment:
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PORT=${REDIS_PORT}
    - REDIS_PASS=${REDIS_PASS}
    - REDIS_ENABLE=true
    - MYSQL_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/admin?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    - MYSQL_USERNAME=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASS}
    - STOCK_BASE_URL=http://${STOCK_TASK_HOST}:${STOCK_TASK_PORT}

  gemini-spider-service:
    image: harbor.emotibot.com/gemini/gemini-spider-service:74b3c43-20201117
    container_name: gemini-spider-service
    ports:
    - 1618:1618
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    environment:
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PORT=${REDIS_PORT}
    - REDIS_PASS=${REDIS_PASS}
    - REDIS_ENABLE=true
    - MINIO_HOST=${MINIO_HOST}
    - MINIO_PORT=${MINIO_PORT}
    - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
    - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    - MYSQL_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/crawl?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    - MYSQL_USERNAME=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASS}
    - CS_WEB_DRIVER_URL=http://${WEBDRIVER_HOST}:${WEBDRIVER_PORT}
    - CS_WEB_DRIVER_MAX_IDLE=1
    - CS_WEB_DRIVER_MAX_TOTAL=2
    - CS_WEB_DRIVER_MIN_IDLE=0
    - CS_WEB_DRIVER_INIT_SIZE=1
    - CS_REDIS_KEY_CRAWLED=crawled
    - SCRIPT_STOCK_TOKEN=script/aes.min.js

networks:
  default:
    external:
      name: emotibot